<x-admin-layout title="الزوار والإحصائيات">
<div class="space-y-6">
    <div class="rounded-2xl border border-purple-800 bg-purple-950/30 p-5"><h2 class="text-xl font-bold mb-2">من أول زيارة… لحد الاشتراك</h2><p class="text-gray-400 text-sm leading-relaxed">بيانات فعلية من وقت تفعيل التتبّع. الزائر المميز محسوب بمعرّف المتصفح، وليس شخصًا مؤكدًا. تحديث الصفحة يعرض أحدث البيانات.</p></div>
    <form class="grid sm:grid-cols-2 lg:grid-cols-6 gap-3 bg-gray-900 p-4 rounded-2xl" method="GET">
        <label class="text-sm">من<input class="checkout-input" type="date" name="from" value="{{ request('from') }}" required></label>
        <label class="text-sm">إلى<input class="checkout-input" type="date" name="to" value="{{ request('to') }}" required></label>
        <label class="text-sm">المصدر<input class="checkout-input" name="source" value="{{ request('source') }}" placeholder="facebook أو direct"></label>
        <label class="text-sm">الجهاز<select name="device" class="checkout-input"><option value="">كل الأجهزة</option>@foreach(['Mobile'=>'موبايل','Desktop'=>'كمبيوتر','Tablet'=>'تابلت'] as $value=>$label)<option value="{{ $value }}" @selected(request('device')===$value)>{{ $label }}</option>@endforeach</select></label>
        <label class="text-sm">بحث<input class="checkout-input" name="q" value="{{ request('q') }}" placeholder="اسم، إيميل، موبايل أو معرّف"></label>
        <div class="flex items-end gap-3"><button class="checkout-submit">عرض</button><a href="{{ route('admin.visitors.index') }}" class="text-sm py-3">مسح</a></div>
    </form>
    @if($errors->any())<p class="text-red-300">{{ $errors->first() }}</p>@endif
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">@foreach(['visitors'=>'زوار مميزون','visits'=>'الزيارات','views'=>'مشاهدات الصفحات','online'=>'نشط خلال 5 دقائق','new'=>'زوار جدد','returning'=>'زوار عائدون','subscribe_clicks'=>'ضغطات الاشتراك','whatsapp_clicks'=>'ضغطات واتساب','plays'=>'مرات فتح اللعب','duration'=>'متوسط التفاعل / ثانية'] as $key=>$label)<div class="bg-gray-900 border border-gray-800 rounded-2xl p-5"><p class="text-gray-400 text-sm">{{ $label }}</p><strong class="block text-3xl mt-3 text-purple-200">{{ number_format($stats[$key]) }}</strong></div>@endforeach</div>
    <section class="bg-gray-900 border border-gray-800 rounded-2xl p-5"><h2 class="font-bold text-lg mb-2">مراحل الاهتمام والاشتراك</h2><p class="text-gray-500 text-xs mb-5">عدد الزوار الذين وصلوا لكل مرحلة في الزيارات المختارة؛ المراحل ليست بالضرورة بالترتيب. التفعيل يُنسب لزيارة رفع الإيصال، حتى لو تمت الموافقة لاحقًا.</p><div class="grid sm:grid-cols-5 gap-4">@foreach($funnel as $name=>$count)<div><p class="text-sm text-gray-300">{{ \App\Models\AnalyticsEvent::LABELS[$name] }}</p><strong class="text-2xl block my-2">{{ $count }}</strong><div class="h-2 rounded bg-gray-800"><div class="h-2 rounded bg-purple-500" style="width:{{ $stats['visitors'] ? min(100,round($count/$stats['visitors']*100)) : 0 }}%"></div></div><small class="text-gray-500">{{ $stats['visitors'] ? round($count/$stats['visitors']*100,1) : 0 }}% من الزوار</small></div>@endforeach</div></section>
    <div class="grid lg:grid-cols-3 gap-4">@foreach(['مصادر الزيارات'=>[$sources,'source'],'الأجهزة'=>[$devices,'device'],'أكثر الصفحات مشاهدة'=>[$pages,'path']] as $heading=>[$rows,$field])<section class="bg-gray-900 border border-gray-800 rounded-2xl p-5"><h2 class="font-bold mb-4">{{ $heading }}</h2>@forelse($rows as $row)<div class="flex justify-between gap-4 border-b border-gray-800 py-3 text-sm"><span class="break-all" dir="auto">{{ $row->$field === 'direct' ? 'مباشر / المصدر غير متاح' : $row->$field }}</span><strong>{{ $row->total }}</strong></div>@empty<p class="text-gray-500">لا توجد بيانات في الفترة المختارة.</p>@endforelse</section>@endforeach</div>
    <section class="bg-gray-900 border border-gray-800 rounded-2xl p-5"><h2 class="font-bold mb-4">الزيارات اليومية <span class="text-gray-500 text-xs">آخر 31 يومًا بها زيارات ضمن الفترة</span></h2><div class="flex items-end gap-2 overflow-x-auto h-40" dir="ltr">@foreach($days as $day)<div class="flex flex-col justify-end items-center shrink-0 h-full" style="width:54px"><small>{{ $day->total }}</small><div class="bg-purple-500 rounded-t w-6" style="height:{{ max(4,100*$day->total/max(1,$days->max('total'))) }}px"></div><small class="text-gray-500 mt-2">{{ substr($day->day,5) }}</small></div>@endforeach</div></section>
    <section class="bg-gray-900 border border-gray-800 rounded-2xl overflow-hidden"><h2 class="p-5 font-bold text-lg">كل الزوار</h2><div class="overflow-x-auto"><table class="w-full text-sm text-right"><thead class="bg-gray-800 text-gray-400"><tr><th class="p-4">الزائر</th><th class="p-4">مصدر آخر زيارة</th><th class="p-4">الجهاز</th><th class="p-4">الزيارات</th><th class="p-4">آخر نشاط</th><th class="p-4">التفاصيل</th></tr></thead><tbody>@forelse($visitors as $visitor)@php($last=$latest->get($visitor->id))<tr class="border-t border-gray-800"><td class="p-4"><strong>{{ $visitor->user?->name ?? 'زائر مجهول' }}</strong><small class="block text-gray-500">{{ substr($visitor->id,0,8) }} · {{ $visitor->user?->email }}</small></td><td class="p-4">{{ $last?->source === 'direct' ? 'مباشر / غير متاح' : $last?->source }}</td><td class="p-4">{{ $last?->device }}<small class="block text-gray-500">{{ $last?->browser }} · {{ $last?->os }}</small></td><td class="p-4">{{ $visitor->filtered_visits_count }}</td><td class="p-4 whitespace-nowrap">{{ $last?->last_seen_at->format('Y-m-d H:i') }}</td><td class="p-4"><a class="text-purple-300 font-bold whitespace-nowrap" href="{{ route('admin.visitors.show',$visitor) }}">رحلة الزائر ←</a></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-gray-400">لسّه مفيش زيارات مطابقة. زيارات الإدارة والروبوتات المعروفة لا تُحتسب.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $visitors->links() }}</div></section>
    <p class="text-xs text-gray-500 leading-relaxed">مدة التفاعل تقديرية أثناء ظهور الصفحة، وتُحدّث كل 30 ثانية. بيانات المصدر والجهاز قد تكون ناقصة أو غير دقيقة. لا نجمع الموقع الدقيق أو محتوى الكتابة. جميع الأوقات بتوقيت {{ config('app.timezone') }}.</p>
</div>
</x-admin-layout>
