<x-admin-layout title="رحلة الزائر">
<a href="{{ route('admin.visitors.index') }}" class="text-purple-300">→ كل الزوار</a>
<section class="bg-gray-900 border border-gray-800 rounded-2xl p-6 my-6"><h2 class="text-2xl font-bold">{{ $visitor->user?->name ?? 'زائر مجهول' }}</h2><p class="text-gray-400 break-all mt-3">المعرّف: {{ $visitor->id }}</p>@if($visitor->user)<p class="mt-3">{{ $visitor->user->email }} · {{ $visitor->user->phone }}</p><a class="text-purple-300 inline-block mt-3" href="{{ route('admin.users.show',$visitor->user) }}">حساب العميل واشتراكاته ←</a>@else<p class="text-gray-500 mt-3">لم يرتبط هذا المتصفح بحساب مسجل بعد.</p>@endif<p class="text-sm text-gray-500 mt-3">أول ظهور: {{ $visitor->created_at->format('Y-m-d H:i') }}. المعرّف يخص المتصفح، وقد يستخدمه أكثر من شخص.</p></section>
<h2 class="text-lg font-bold mb-4">الزيارات ومصدر كل زيارة</h2>
<div class="space-y-4">@foreach($visits as $visit)<section class="bg-gray-900 border border-gray-800 rounded-2xl p-5"><div class="flex justify-between flex-wrap gap-3"><strong>{{ $visit->created_at->format('Y-m-d H:i') }}</strong><span class="text-purple-300">{{ $visit->source === 'direct' ? 'مباشر / المصدر غير متاح' : $visit->source }}</span></div><dl class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-5 text-sm">@foreach([
'الموقع المُحيل'=>$visit->referrer_host,'الحملة'=>$visit->campaign,'نوع المصدر'=>$visit->medium,'صفحة الدخول'=>$visit->landing_path,'آخر صفحة'=>$visit->last_path,'الجهاز'=>$visit->device,'المتصفح'=>$visit->browser,'النظام'=>$visit->os,'لغة المتصفح'=>$visit->language,'المنطقة الزمنية المبلّغ عنها'=>$visit->timezone,'دقة الشاشة'=>$visit->screen,'شبكة IP مخفية جزئيًا'=>$visit->ip_network,'الدولة / المدينة'=>null,'مدة التفاعل التقريبية'=>$visit->active_seconds.' ثانية','آخر نشاط'=>$visit->last_seen_at->format('Y-m-d H:i'),'عدد الأحداث'=>$visit->events_count
] as $label=>$value)<div><dt class="text-gray-500 mb-1">{{ $label }}</dt><dd class="break-all" dir="auto">{{ $value ?? 'غير متاحة' }}</dd></div>@endforeach</dl><small class="text-gray-600 block mt-4">معرّف الزيارة: {{ $visit->id }}</small></section>@endforeach</div><div class="my-4">{{ $visits->withQueryString()->links() }}</div>
<section class="bg-gray-900 border border-gray-800 rounded-2xl p-5 mt-8"><h2 class="text-lg font-bold mb-5">سجل النشاط <span class="text-gray-500 text-xs">الأحدث أولًا</span></h2>@forelse($events as $event)<div class="border-r-2 border-purple-700 pr-4 pb-5"><div class="flex flex-wrap justify-between gap-3"><strong>{{ $event->label }}</strong><time class="text-gray-500 text-xs">{{ $event->created_at->format('Y-m-d H:i:s') }}</time></div><p class="text-gray-400 text-sm break-all mt-2" dir="auto">{{ $event->path }}</p>@if($event->detail)<p class="text-purple-300 text-sm mt-1">{{ in_array($event->name,['receipt_uploaded','subscription_approved']) ? 'رقم طلب الاشتراك: ' : '' }}{{ $event->detail }}</p>@endif<small class="text-gray-600">زيارة {{ substr($event->visit_id,0,8) }}</small></div>@empty<p class="text-gray-500">لا توجد أحداث.</p>@endforelse{{ $events->withQueryString()->links() }}</section>
</x-admin-layout>
